# Generated by Django 5.2.1 on 2025-06-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetitem',
            name='minutes_worked',
        ),
    ]
