# Generated by Django 5.2.1 on 2025-06-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_timesheetitem_minutes_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetitem',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
