# Generated by Django 5.2.1 on 2025-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_timesheetitem_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='tasks',
            field=models.ManyToManyField(through='main_app.TimesheetItem', to='main_app.task'),
        ),
    ]
