# Generated by Django 5.2.1 on 2025-06-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_timesheet_tasks_timesheet_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='items',
            new_name='timesheet_items',
        ),
    ]
