# Generated by Django 5.2.1 on 2025-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_items_timesheet_timesheet_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='timesheet_items',
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
