# Generated by Django 5.2.1 on 2025-06-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_timesheet_timesheet_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetitem',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.timesheet'),
        ),
    ]
