# Generated by Django 5.2.1 on 2025-06-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_timesheetitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheetitem',
            unique_together={('timesheet', 'task')},
        ),
    ]
